name: "Gibble Action"
description: "GitHub Action for processing changed files"
inputs:
  github_token:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}
  project_id:
    description: "Project ID"
    required: true
  api_key:
    description: "API Key"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
