name: "Gibble Workflows"
description: "Sync context for your voice agents with your github docs."
author: "Gibble AI"
inputs:
  project_id:
    description: "Project ID"
    required: true
  api_key:
    description: "API Key"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}
  full_scan:
    description: "If you want a full code scan of your repository, defaults to false"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "out/index.js"
branding:
  icon: "book"
  color: "gray-dark"